# Site settings
title: QuickPoll Feature preview
email: your_email@example.com
author: 
description: > # this means to ignore newlines until "baseurl:"
  This website's goal is to show you what our next Web application
  'QuickPoll' will be able to do for you. Are you a teacher ? You
  will be able to gather information from your audience in no time!
baseurl:     "/twebpres"
url:         "http://julienamacher.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
date_format: "%Y-%m-%d"