# Site settings
title: QuickPoll Feature preview
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This website's goal is to show you what our next Web application
  'QuickPoll' will be able to do for you. Are you a teacher ? You
  will be able to gather information from your audience in no time!
baseurl: "/twebpres" # the subpath of your site, e.g. /blog/
url: "http://julienamacher.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
